export const SET_AVAILABLE_CITIES = "SET_AVAILABLE_CITIES";
export const SET_AVAILABLE_SPECIALITIES = "SET_AVAILABLE_SPECIALITIES";
export const SET_SEARCHED_SUBCONTRACTORS = "SET_SEARCHED_SUBCONTRACTORS";
export const SET_LOADING = "SET_LOADING";
export const SET_IS_DIRTY = "SET_IS_DIRTY";
